import type { Metadata } from "next";
import { Cherry_Bomb_One, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

const cherryBombOne = Cherry_Bomb_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-logo",
});

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["600"],
  variable: "--font-nav",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${cherryBombOne.variable} ${ibmPlexSans.variable}`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
